default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    
    - main.less: { position: last }
  
  javascripts:
    # Required for blog slots
    - /apostropheBlogPlugin/js/aBlog.js
    - /sfGoogleLoginPlugin/js/sfGoogleLogin.js
    - /js/tabs.js

  has_layout:     true
  layout:         layout
