default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    
    - main.css: { position: last }
  
  javascripts:
    # Required for blog slots
    - /apostropheBlogPlugin/js/aBlog.js
    - site.js: { position: last }

  has_layout:     true
  layout:         layout
