<?php

/**
 * BaseGoogleAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $user_token
 * @property integer $sf_guard_user_id
 * @property sfGuardUser $sfGuardUser
 * 
 * @method string        getUserToken()        Returns the current record's "user_token" value
 * @method integer       getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method sfGuardUser   getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method GoogleAccount setUserToken()        Sets the current record's "user_token" value
 * @method GoogleAccount setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method GoogleAccount setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * 
 * @package    SzI www
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGoogleAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('google_account');
        $this->hasColumn('user_token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));
    }
}